# Automatically generated by configure - do not modify

all:
CONFIG_POSIX=y
CONFIG_LINUX=y
SRC_PATH=/home/cloud-user/qemu-8.1.2
TARGET_DIRS=ppc64-softmmu
CONFIG_PLUGIN=y
ROMS=
PYTHON=/home/cloud-user/qemu-8.1.2/build/pyvenv/bin/python3.9 -B
GENISOIMAGE=/usr/bin/genisoimage
MESON=/home/cloud-user/qemu-8.1.2/build/pyvenv/bin/meson
NINJA=/usr/bin/ninja
PKG_CONFIG=pkg-config
CC=cc
EXESUF=
TCG_TESTS_TARGETS=
