#pragma GCC poison CONFIG_AC97
#pragma GCC poison CONFIG_ACPI
#pragma GCC poison CONFIG_ACPI_ERST
#pragma GCC poison CONFIG_ACPI_SMBUS
#pragma GCC poison CONFIG_ADB
#pragma GCC poison CONFIG_ADLIB
#pragma GCC poison CONFIG_AHCI
#pragma GCC poison CONFIG_AHCI_ICH9
#pragma GCC poison CONFIG_APM
#pragma GCC poison CONFIG_AT24C
#pragma GCC poison CONFIG_ATI_VGA
#pragma GCC poison CONFIG_BITBANG_I2C
#pragma GCC poison CONFIG_BOCHS_DISPLAY
#pragma GCC poison CONFIG_CAN_BUS
#pragma GCC poison CONFIG_CAN_CTUCANFD
#pragma GCC poison CONFIG_CAN_CTUCANFD_PCI
#pragma GCC poison CONFIG_CAN_PCI
#pragma GCC poison CONFIG_CAN_SJA1000
#pragma GCC poison CONFIG_CHRP_NVRAM
#pragma GCC poison CONFIG_CS4231A
#pragma GCC poison CONFIG_CUDA
#pragma GCC poison CONFIG_DDC
#pragma GCC poison CONFIG_DEC_PCI
#pragma GCC poison CONFIG_DIMM
#pragma GCC poison CONFIG_DS1338
#pragma GCC poison CONFIG_E1000E_PCI_EXPRESS
#pragma GCC poison CONFIG_E1000_PCI
#pragma GCC poison CONFIG_E500
#pragma GCC poison CONFIG_E500PLAT
#pragma GCC poison CONFIG_EDID
#pragma GCC poison CONFIG_EDU
#pragma GCC poison CONFIG_EEPRO100_PCI
#pragma GCC poison CONFIG_ES1370
#pragma GCC poison CONFIG_ESCC
#pragma GCC poison CONFIG_ESP
#pragma GCC poison CONFIG_ESP_PCI
#pragma GCC poison CONFIG_ETSEC
#pragma GCC poison CONFIG_FDC
#pragma GCC poison CONFIG_FDC_ISA
#pragma GCC poison CONFIG_FDT_PPC
#pragma GCC poison CONFIG_FSDEV_9P
#pragma GCC poison CONFIG_FW_CFG_PPC
#pragma GCC poison CONFIG_GENERIC_LOADER
#pragma GCC poison CONFIG_GPIO_MPC8XXX
#pragma GCC poison CONFIG_GRACKLE_PCI
#pragma GCC poison CONFIG_GUEST_LOADER
#pragma GCC poison CONFIG_GUS
#pragma GCC poison CONFIG_HDA
#pragma GCC poison CONFIG_HEATHROW_PIC
#pragma GCC poison CONFIG_I2C
#pragma GCC poison CONFIG_I386_DIS
#pragma GCC poison CONFIG_I82374
#pragma GCC poison CONFIG_I82378
#pragma GCC poison CONFIG_I8254
#pragma GCC poison CONFIG_I8257
#pragma GCC poison CONFIG_I8259
#pragma GCC poison CONFIG_I82801B11
#pragma GCC poison CONFIG_IDE_CORE
#pragma GCC poison CONFIG_IDE_ISA
#pragma GCC poison CONFIG_IDE_MACIO
#pragma GCC poison CONFIG_IDE_PCI
#pragma GCC poison CONFIG_IDE_QDEV
#pragma GCC poison CONFIG_IDE_SII3112
#pragma GCC poison CONFIG_IDE_VIA
#pragma GCC poison CONFIG_IGB_PCI_EXPRESS
#pragma GCC poison CONFIG_IMX_USBPHY
#pragma GCC poison CONFIG_IOH3420
#pragma GCC poison CONFIG_IPACK
#pragma GCC poison CONFIG_IPMI
#pragma GCC poison CONFIG_IPMI_EXTERN
#pragma GCC poison CONFIG_IPMI_LOCAL
#pragma GCC poison CONFIG_ISA_BUS
#pragma GCC poison CONFIG_ISA_IPMI_BT
#pragma GCC poison CONFIG_ISA_SUPERIO
#pragma GCC poison CONFIG_ISA_TESTDEV
#pragma GCC poison CONFIG_IVSHMEM_DEVICE
#pragma GCC poison CONFIG_LSI_SCSI_PCI
#pragma GCC poison CONFIG_M41T80
#pragma GCC poison CONFIG_M48T59
#pragma GCC poison CONFIG_MAC_DBDMA
#pragma GCC poison CONFIG_MACIO
#pragma GCC poison CONFIG_MACIO_GPIO
#pragma GCC poison CONFIG_MAC_NEWWORLD
#pragma GCC poison CONFIG_MAC_NVRAM
#pragma GCC poison CONFIG_MAC_OLDWORLD
#pragma GCC poison CONFIG_MAC_PMU
#pragma GCC poison CONFIG_MC146818RTC
#pragma GCC poison CONFIG_MEGASAS_SCSI_PCI
#pragma GCC poison CONFIG_MEM_DEVICE
#pragma GCC poison CONFIG_MOS6522
#pragma GCC poison CONFIG_MPC8544DS
#pragma GCC poison CONFIG_MPC_I2C
#pragma GCC poison CONFIG_MPTSAS_SCSI_PCI
#pragma GCC poison CONFIG_MSI_NONBROKEN
#pragma GCC poison CONFIG_MV64361
#pragma GCC poison CONFIG_NE2000_COMMON
#pragma GCC poison CONFIG_NE2000_ISA
#pragma GCC poison CONFIG_NE2000_PCI
#pragma GCC poison CONFIG_NMC93XX_EEPROM
#pragma GCC poison CONFIG_NVDIMM
#pragma GCC poison CONFIG_NVME_PCI
#pragma GCC poison CONFIG_OPENPIC
#pragma GCC poison CONFIG_OR_IRQ
#pragma GCC poison CONFIG_PARALLEL
#pragma GCC poison CONFIG_PC87312
#pragma GCC poison CONFIG_PCI
#pragma GCC poison CONFIG_PCI_DEVICES
#pragma GCC poison CONFIG_PCIE_PCI_BRIDGE
#pragma GCC poison CONFIG_PCIE_PORT
#pragma GCC poison CONFIG_PCI_EXPRESS
#pragma GCC poison CONFIG_PCI_POWERNV
#pragma GCC poison CONFIG_PCI_TESTDEV
#pragma GCC poison CONFIG_PCKBD
#pragma GCC poison CONFIG_PCNET_COMMON
#pragma GCC poison CONFIG_PCNET_PCI
#pragma GCC poison CONFIG_PCSPK
#pragma GCC poison CONFIG_PEGASOS2
#pragma GCC poison CONFIG_PFLASH_CFI01
#pragma GCC poison CONFIG_PFLASH_CFI02
#pragma GCC poison CONFIG_PLATFORM_BUS
#pragma GCC poison CONFIG_POWERNV
#pragma GCC poison CONFIG_PPC405
#pragma GCC poison CONFIG_PPC440
#pragma GCC poison CONFIG_PPC4XX
#pragma GCC poison CONFIG_PPC_DIS
#pragma GCC poison CONFIG_PPCE500_PCI
#pragma GCC poison CONFIG_PPC_UIC
#pragma GCC poison CONFIG_PREP
#pragma GCC poison CONFIG_PS2
#pragma GCC poison CONFIG_PSERIES
#pragma GCC poison CONFIG_PTIMER
#pragma GCC poison CONFIG_PVPANIC_COMMON
#pragma GCC poison CONFIG_PVPANIC_PCI
#pragma GCC poison CONFIG_RAVEN_PCI
#pragma GCC poison CONFIG_ROCKER
#pragma GCC poison CONFIG_RS6000_MC
#pragma GCC poison CONFIG_RTL8139_PCI
#pragma GCC poison CONFIG_SAM460EX
#pragma GCC poison CONFIG_SB16
#pragma GCC poison CONFIG_SCSI
#pragma GCC poison CONFIG_SD
#pragma GCC poison CONFIG_SDHCI
#pragma GCC poison CONFIG_SDHCI_PCI
#pragma GCC poison CONFIG_SERIAL
#pragma GCC poison CONFIG_SERIAL_ISA
#pragma GCC poison CONFIG_SERIAL_PCI
#pragma GCC poison CONFIG_SERIAL_PCI_MULTI
#pragma GCC poison CONFIG_SM501
#pragma GCC poison CONFIG_SMBUS
#pragma GCC poison CONFIG_SMBUS_EEPROM
#pragma GCC poison CONFIG_SPAPR_RNG
#pragma GCC poison CONFIG_SPAPR_VSCSI
#pragma GCC poison CONFIG_SUNGEM
#pragma GCC poison CONFIG_SYSTEM_ONLY
#pragma GCC poison CONFIG_TEST_DEVICES
#pragma GCC poison CONFIG_TPM_BACKEND
#pragma GCC poison CONFIG_TPM_EMULATOR
#pragma GCC poison CONFIG_TPM_PASSTHROUGH
#pragma GCC poison CONFIG_TPM_SPAPR
#pragma GCC poison CONFIG_TULIP
#pragma GCC poison CONFIG_UNIMP
#pragma GCC poison CONFIG_UNIN_PCI
#pragma GCC poison CONFIG_USB
#pragma GCC poison CONFIG_USB_AUDIO
#pragma GCC poison CONFIG_USB_CANOKEY
#pragma GCC poison CONFIG_USB_EHCI
#pragma GCC poison CONFIG_USB_EHCI_PCI
#pragma GCC poison CONFIG_USB_EHCI_SYSBUS
#pragma GCC poison CONFIG_USB_NETWORK
#pragma GCC poison CONFIG_USB_OHCI
#pragma GCC poison CONFIG_USB_OHCI_PCI
#pragma GCC poison CONFIG_USB_SERIAL
#pragma GCC poison CONFIG_USB_SMARTCARD
#pragma GCC poison CONFIG_USB_STORAGE_BOT
#pragma GCC poison CONFIG_USB_STORAGE_CLASSIC
#pragma GCC poison CONFIG_USB_STORAGE_CORE
#pragma GCC poison CONFIG_USB_STORAGE_MTP
#pragma GCC poison CONFIG_USB_STORAGE_UAS
#pragma GCC poison CONFIG_USB_TABLET_WACOM
#pragma GCC poison CONFIG_USB_U2F
#pragma GCC poison CONFIG_USB_UHCI
#pragma GCC poison CONFIG_USB_XHCI
#pragma GCC poison CONFIG_USB_XHCI_NEC
#pragma GCC poison CONFIG_USB_XHCI_PCI
#pragma GCC poison CONFIG_VFIO
#pragma GCC poison CONFIG_VFIO_AMD_XGBE
#pragma GCC poison CONFIG_VFIO_PCI
#pragma GCC poison CONFIG_VFIO_PLATFORM
#pragma GCC poison CONFIG_VFIO_XGMAC
#pragma GCC poison CONFIG_VGA
#pragma GCC poison CONFIG_VGA_CIRRUS
#pragma GCC poison CONFIG_VGA_PCI
#pragma GCC poison CONFIG_VHOST_SCSI
#pragma GCC poison CONFIG_VHOST_SCSI_COMMON
#pragma GCC poison CONFIG_VHOST_USER_BLK
#pragma GCC poison CONFIG_VHOST_USER_FS
#pragma GCC poison CONFIG_VHOST_USER_GPIO
#pragma GCC poison CONFIG_VHOST_USER_GPU
#pragma GCC poison CONFIG_VHOST_USER_I2C
#pragma GCC poison CONFIG_VHOST_USER_INPUT
#pragma GCC poison CONFIG_VHOST_USER_RNG
#pragma GCC poison CONFIG_VHOST_USER_SCMI
#pragma GCC poison CONFIG_VHOST_USER_SCSI
#pragma GCC poison CONFIG_VHOST_USER_VGA
#pragma GCC poison CONFIG_VHOST_USER_VSOCK
#pragma GCC poison CONFIG_VHOST_VDPA_DEV
#pragma GCC poison CONFIG_VHOST_VSOCK
#pragma GCC poison CONFIG_VHOST_VSOCK_COMMON
#pragma GCC poison CONFIG_VIRTEX
#pragma GCC poison CONFIG_VIRTIO
#pragma GCC poison CONFIG_VIRTIO_9P
#pragma GCC poison CONFIG_VIRTIO_BALLOON
#pragma GCC poison CONFIG_VIRTIO_BLK
#pragma GCC poison CONFIG_VIRTIO_CRYPTO
#pragma GCC poison CONFIG_VIRTIO_GPU
#pragma GCC poison CONFIG_VIRTIO_INPUT
#pragma GCC poison CONFIG_VIRTIO_INPUT_HOST
#pragma GCC poison CONFIG_VIRTIO_IOMMU
#pragma GCC poison CONFIG_VIRTIO_NET
#pragma GCC poison CONFIG_VIRTIO_PCI
#pragma GCC poison CONFIG_VIRTIO_RNG
#pragma GCC poison CONFIG_VIRTIO_SCSI
#pragma GCC poison CONFIG_VIRTIO_SERIAL
#pragma GCC poison CONFIG_VIRTIO_VGA
#pragma GCC poison CONFIG_VMW_PVSCSI_SCSI_PCI
#pragma GCC poison CONFIG_VMXNET3_PCI
#pragma GCC poison CONFIG_VOF
#pragma GCC poison CONFIG_VT82C686
#pragma GCC poison CONFIG_WDT_IB6300ESB
#pragma GCC poison CONFIG_WDT_IB700
#pragma GCC poison CONFIG_XICS
#pragma GCC poison CONFIG_XILINX
#pragma GCC poison CONFIG_XILINX_ETHLITE
#pragma GCC poison CONFIG_XIO3130
#pragma GCC poison CONFIG_XIVE
#pragma GCC poison QEMU_ARCH
#pragma GCC poison TARGET_BIG_ENDIAN
#pragma GCC poison TARGET_NAME
#pragma GCC poison TARGET_NEED_FDT
#pragma GCC poison TARGET_PPC
#pragma GCC poison TARGET_PPC64
#pragma GCC poison TARGET_SUPPORTS_MTTCG
